export const GET_ALL_POSTS_REQUEST = '@GET_ALL_POSTS_REQUEST'
export const GET_ALL_POSTS_SUCCESS = '@GET_ALL_POSTS_SUCCESS'
export const GET_ALL_POSTS_FAILURE = '@GET_ALL_POSTS_FAILURE'

export const CREATE_POST_REQUEST = '@CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = '@CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = '@CREATE_POST_FAILURE'

export const EDIT_POST_REQUEST = '@EDIT_POST_REQUEST'
export const EDIT_POST_SUCCESS = '@EDIT_POST_SUCCESS'
export const EDIT_POST_FAILURE = '@EDIT_POST_FAILURE'

export const DELETE_POST_REQUEST = '@DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = '@DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = '@DELETE_POST_FAILURE'
